/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Hyllmee
 */
public class PajakApp extends javax.swing.JFrame {

    /**
     * Creates new form PajakApp
     */
    public PajakApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        isinama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        isipenghasilan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pilihjumlahkendaraan = new javax.swing.JComboBox<>();
        hitung = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        isipajak = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridLayout(15, 2));

        jLabel12.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.add(jLabel12);

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setText("           Aplikasi Hitung Pajak");
        jPanel1.add(jLabel1);
        jPanel1.add(jLabel9);

        jLabel2.setText("   Nama:");
        jPanel1.add(jLabel2);
        jPanel1.add(isinama);

        jLabel5.setText("  Penghasilan :");
        jPanel1.add(jLabel5);
        jPanel1.add(isipenghasilan);

        jLabel6.setText("  Jumlah Kendaraan :");
        jPanel1.add(jLabel6);

        pilihjumlahkendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak  Punya", "1", "2", "3", "4", "5" }));
        jPanel1.add(pilihjumlahkendaraan);

        hitung.setBackground(new java.awt.Color(0, 153, 153));
        hitung.setText("Hitung Pajak");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        jPanel1.add(hitung);

        jLabel11.setText("  Jumlah Pajak :");
        jPanel1.add(jLabel11);
        jPanel1.add(jLabel8);
        jPanel1.add(isipajak);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        double penghasilan = Double.parseDouble(isipenghasilan.getText());
        int jumlahKendaraan = pilihjumlahkendaraan.getSelectedIndex();

        double pajak = perhitungan(penghasilan, jumlahKendaraan);
        
        isipajak.setText(String.format("%.2f", pajak));
    }//GEN-LAST:event_hitungActionPerformed
    
    private double perhitungan(double penghasilan, int jumlahKendaraan) {
        double pajak = 0;

        if (penghasilan >= 10_000_000 && jumlahKendaraan == 3) {
            pajak = penghasilan * 0.15;
        } else if (penghasilan >= 5_000_000 && jumlahKendaraan == 2) {
            pajak = penghasilan * 0.10;
        } else if (penghasilan >= 5_000_000 && jumlahKendaraan == 1) {
            pajak = penghasilan * 0.07;
        } else if (penghasilan < 5_000_000 && jumlahKendaraan == 1) {
            pajak = penghasilan * 0.05;
        } else if (penghasilan < 5_000_000 && jumlahKendaraan == 0) {
            pajak = penghasilan * 0.025;
        }

        return pajak;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PajakApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PajakApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PajakApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PajakApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PajakApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hitung;
    private javax.swing.JTextField isinama;
    private javax.swing.JLabel isipajak;
    private javax.swing.JTextField isipenghasilan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> pilihjumlahkendaraan;
    // End of variables declaration//GEN-END:variables
}
